# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnalysisOrchestrationResult": types.AnalysisOrchestrationResult,
    "stream_types.AnalysisOrchestrationResult": stream_types.AnalysisOrchestrationResult,

    "types.AnalysisTask": types.AnalysisTask,
    "stream_types.AnalysisTask": stream_types.AnalysisTask,

    "types.BoundingBox": types.BoundingBox,
    "stream_types.BoundingBox": stream_types.BoundingBox,

    "types.ContentRelevanceResult": types.ContentRelevanceResult,
    "stream_types.ContentRelevanceResult": stream_types.ContentRelevanceResult,

    "types.DataRequest": types.DataRequest,
    "stream_types.DataRequest": stream_types.DataRequest,

    "types.LanguageAnalysisResult": types.LanguageAnalysisResult,
    "stream_types.LanguageAnalysisResult": stream_types.LanguageAnalysisResult,

    "types.PersonalDataResult": types.PersonalDataResult,
    "stream_types.PersonalDataResult": stream_types.PersonalDataResult,

    "types.PolicyAnalysisResult": types.PolicyAnalysisResult,
    "stream_types.PolicyAnalysisResult": stream_types.PolicyAnalysisResult,

    "types.PolicyLink": types.PolicyLink,
    "stream_types.PolicyLink": stream_types.PolicyLink,

    "types.TrademarkAnalysisResult": types.TrademarkAnalysisResult,
    "stream_types.TrademarkAnalysisResult": stream_types.TrademarkAnalysisResult,

    "types.TrademarkViolation": types.TrademarkViolation,
    "stream_types.TrademarkViolation": stream_types.TrademarkViolation,

    "types.WebsiteCompletenessResult": types.WebsiteCompletenessResult,
    "stream_types.WebsiteCompletenessResult": stream_types.WebsiteCompletenessResult,


    "types.AnalysisPriority": types.AnalysisPriority,

    "types.BusinessLegitimacy": types.BusinessLegitimacy,

    "types.CompletenessLevel": types.CompletenessLevel,

    "types.ComplianceLevel": types.ComplianceLevel,

    "types.ConfidenceLevel": types.ConfidenceLevel,

    "types.DataSensitivity": types.DataSensitivity,

    "types.LanguageQuality": types.LanguageQuality,

    "types.LanguageSupport": types.LanguageSupport,

    "types.RelevanceLevel": types.RelevanceLevel,

    "types.ViolationType": types.ViolationType,

}